// request to POST localhost:3000/generate with json body

POST https://ditto-stg.musicorum.cloud/generate
Content-Type: application/json

{"theme":"classic_collage","data":{"rows":3,"columns":3,"entity":"artist","padded":false,"show_labels":false,"period":"overall","username":"blueslimee"}}
